sudo:
  false

language:
  python

python:
  - 2.7

services:
  - docker

install:
  - make install
  - make build

script:
  - make test

deploy:
  - provider: script
    script: make push
    on:
      branch: master
